### ISSUE TITLE
Played Tracks Not Added to Spotify Recently Played

### ISSUE THREAD

**Issue by glk1001** [michaelherger/librespot#14]
Hi, I noticed quite a while back this issue was raised by you with librespot. I can't figure out what became of this issue. I think maybe it's on a librespot to-do list. What is your understanding of what's happening?

**Comment by michaelherger** [comment]
The relevant discussion is still in https://github.com/librespot-org/librespot/discussions/626 - which hasn't seen any update in more than a year. I would assume reporting still isn't working in the latest code base (which hasn't been released yet). Please ask there again. I'd be interested in learning about any news. Thanks!

**Comment by glk1001** [comment]
The answer from Roderick van Domburg was 'Still not implemented'.
