### ISSUE TITLE
Can Spotty Be Made to Work on Android

### ISSUE THREAD

**Issue by glk1001** [michaelherger/librespot#15]
Hi, I'm trying to get the 'plugin.audio.spotify' plugin going again for Kodi (https://github.com/glk1001/plugin.audio.spotify). It works fine with the latest Spotty on Windows 10 and Ubuntu 22.04. Someone tried it on Android  and it didn't work. From what I can see Spotty is not designed to work on Android. Is this the case?

**Comment by michaelherger** [comment]
I'm sorry to send you elsewhere again 😀. But that's a question you'd have to ask the Kodi plugin author. I have no clue how they integrate with Spotty. I certainly don't provide binaries for Android, as that's not a target platform for LMS. They "only" might have to build the helper for android and add whatever glue they're using to run it.

**Comment by michaelherger** [comment]
Hah... they're funny: readme says "Create issue in Github.", but the issues feature is disabled 🤦🏻.

**Comment by glk1001** [comment]
Yes, the github kodi Spotify plugin is pretty much dead. I've forked it (https://github.com/glk1001/plugin.audio.spotify) and cleaned and stripped unused code so I have a better idea of how it works now. To run 'Spotty', the code does a platform check for Windows, Mac, or linux, then runs the appropriate Spotty binary as a Python command line process. So I guess my question is, is there is no way to run Spotty as a command line process on Android?

**Comment by michaelherger** [comment]
Oh, that's your repository... you should edit the readme or re-enable issues 😉.

I don't know about running things on Android. But first of all there's no Android binary of the spotty helper application. Which could become a daunting task, as there are many Android platforms. I have no experience compiling for Android. But it's supposed to be supported (see https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-2). Good luck with that!...

**Comment by glk1001** [comment]
Thanks for that, I'll have a look (and I enabled issues).
