### ISSUE TITLE
Some *(new?) albums are skipping songs instantly - only on Spotify Connect

### ISSUE THREAD

**Issue by thomaswwp** [michaelherger/librespot#18]
We use the Spotify Connect aspect of Spotty almost exclusively and it works beautifully. Recently my daughter started noticing that new albums are skipping after 1s of each track. 

- Hozier: Unheard
- Declan Mckenna: What Happened to the Beach?

This is not an exclusive list but reliably don't work.

When I play them with spotty through the LMS web interface they play perfectly. It is only Spotify Connect that does not work.

### LMS: 
docker container running as "host" image on a Raspberry Pi4: lmscommunity/logitechmediaserver:stable

- Logitech Media Server Version: 8.5.1 - 1712473975 @ Mon Apr 8 04:13:10 CEST 2024
- Server HTTP Port Number: 9000
- Operating system: Debian (Docker) - EN - utf8
- Platform Architecture: aarch64-linux
- Database Version: SQLite

### Player:
Raspberry Pi3B - quite old but works fine, max2play appears abandoned though so I may look at updating it
(we run two Squeezebox Radios but not as Spotify Connect devices - if I enable them as devices we get the same effect, so I guess it it not player related)

- Player Model: SqueezeLite
- Player Type: squeezelite
- Firmware: Max2Play v1.0.3 based on v1.8.7-999

### Other information

- In Spotify developer site I have all the potential users entered as authorised users.
- I have none of the check boxes ticked at the bottom of settings
- I do have my Client ID entered (or nothing works)
- We usually run as one user as a "jam" but in testing the effect is seen with any user set up on Spotty

The relevant few seconds of trying to play Hozier are in the attached log with Spotty on "Info".

[server.log](https://github.com/michaelherger/librespot/files/14905421/server.log)

**Comment by michaelherger** [comment]
Are you sure this is limited to new releases? Spotty in Connect mode is known to be a bit unstable (see eg. https://github.com/michaelherger/Spotty-Plugin/issues/82).

**Comment by thomaswwp** [comment]
Sorry, I thought I was on the plugin repo - not sure how I ended here. I will close this.

In answer to your quesition, my daughters have only brought it to my intention about these new tracks, so I don't knnow if it is exclusively them.

Did some testing today:
1. Spotty - skip skip skip on those albums above
2. HiFiBerry - plays the first song, then gets to the end and plays silence without going to the next track
3. Raspotify - works as expected - one song to the next
