### ISSUE TITLE
Announce Squeezebox players with multiple accounts

### ISSUE THREAD

**Issue by mr-manuel** [michaelherger/librespot#21]
Hello,

first of all thank you for this great plugin!

I'm experiencing some issues with the announcement of the Squeezebox players for the second (out of two) Spotify account. The first account sees all players, but the second account sees only the first player in the list. In this case `Don't announce Squeezebox players running in Spotify Connect mode in your network. Check this option if you don't want your Spotify Connect enabled Squeezebox player to show up in all Spotify apps in your network.` is checked. If I uncheck it, then obviously it works.

I'm using a Spotify Client ID and the second user is added on the User Management page for the inserted key. Both accounts have premium.

Does also someone else have this issue?

I put the log to debug, but I found no data that could help me. Any tips for what to search for?

**Comment by michaelherger** [comment]
I don't understand your question: you tell Spotty not to announce the players in your network. Why would you expect them still to be seen? 

The one account seeing it is not seeing it on the network, but through Spotify's servers. But the other accounts don't see it, because it's connected to the first account. If one of them is seeing both then this probably is some caching, and would go away after a while?

**Comment by mr-manuel** [comment]
Somehow I thought that this option shows the player only to connected accounts and not for other accounts, e.g. when friends are in my WiFi.

Now I understood this better thanks. It happened now to me, that the flag for this option `Don't accounce Squeezebox players...` was set again already two times, always after a LMS update. I'm using the [MS4H](https://music-server.net/) system.

Have you a hint on how to troubleshoot that? Other settings are preserved from the plugin, so this is very odd.

**Comment by michaelherger** [comment]
what is MS4H, and how does it integrate with LMS?

**Comment by mr-manuel** [comment]
Sorry, MS4H is [Music Server 4 Home](https://music-server.net/) which is a bundle to integrate the LMS with Loxone.

**Comment by michaelherger** [comment]
I think this can happen if the helper crashes repeatedly, as there are some incompatibilities on some systems. Please check your server.log: there would be a hint about the daemon crashing (Settings/Information). What other software would be running on the system where LMS is living?

**Comment by mr-manuel** [comment]
In the logs there are no crashes. Today the setting was again lost, even without update. I tried to set it again, made an update, but the setting is still correct. Has to be something other. Now I selected the `Spotty Helper Application` manually instead of automatic. Maybe that helps.

`disableDiscovery` is correctly set to `~` in `/var/lib/squeezeboxserver/prefs/plugin/spotty.prefs` when disabled and to `on` when enabled.

This are the services from the GUI:
![grafik](https://github.com/user-attachments/assets/105ea3fe-ad70-432c-82bd-544113f80ee4)

This from the command line:
```bash
root@ms4h:~# systemctl --type=service --state=running
  UNIT                      LOAD   ACTIVE SUB     DESCRIPTION
  acpi-fakekey.service      loaded active running ACPI fakekey daemon
  acpid.service             loaded active running ACPI event daemon
  apache2.service           loaded active running The Apache HTTP Server
  autofs.service            loaded active running Automounts filesystems on demand
  avahi-daemon.service      loaded active running Avahi mDNS/DNS-SD Stack
  cron.service              loaded active running Regular background program processing daemon
  dbus.service              loaded active running D-Bus System Message Bus
  getty@tty1.service        loaded active running Getty on tty1
  nmbd.service              loaded active running Samba NMB Daemon
  qemu-guest-agent.service  loaded active running QEMU Guest Agent
  rc-local.service          loaded active running /etc/rc.local Compatibility
  rpcbind.service           loaded active running RPC bind portmap service
  rsyslog.service           loaded active running System Logging Service
  smbd.service              loaded active running Samba SMB Daemon
  ssh.service               loaded active running OpenBSD Secure Shell server
  systemd-journald.service  loaded active running Journal Service
  systemd-logind.service    loaded active running User Login Management
  systemd-timesyncd.service loaded active running Network Time Synchronization
  systemd-udevd.service     loaded active running Rule-based Manager for Device Events and Files
  telegraf.service          loaded active running Telegraf
  user@0.service            loaded active running User Manager for UID 0

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
21 loaded units listed.
```

**Comment by michaelherger** [comment]
Did you check LMS' server.log?

**Comment by mr-manuel** [comment]
Yes. I wrote a script now, that notifies me, when the option gets changed. This way I can check what happens at this moment.

**Comment by mr-manuel** [comment]
Seems that this was a LMS bug. Since the latest LMS update this did not happen again.
